## Some heading to talk about project

In [10]:
import numpy as np
import pptk

# Load the point cloud data
target_data = []
filename = 'ENVISAT.fbx.xyz'
with open(filename,'r') as f:
    for line in f.readlines():
        line_data = line.split()
        x, y, z = line_data
        target_data.append([float(x), float(y), float(z)])

In [11]:
# Visualize the target model
v = pptk.viewer(target_data)

### Generating Point Cloud Data


In [17]:
# Transformation matrices
def transform(phi, theta, gamma):
    ''' Creates the transform matrix R
    ARGS:
        phi (rad):      rotation about x-axis
        theta (rad):    rotation about y-axis
        gamma(rad):     rotation about z-axis
    '''
    R_x = np.array([
        [1,  0,            0          ],
        [0,  np.cos(phi),  np.sin(phi)],
        [0, -np.sin(phi),  np.cos(phi)]
    ])
    R_y = np.array([
        [np.cos(theta), 0, -np.sin(theta)],
        [0,             1,  0            ],
        [np.sin(theta), 0,  np.cos(theta)]
    ])
    R_z = np.array([
        [ np.cos(gamma), np.sin(gamma), 0],
        [-np.sin(gamma), np.cos(gamma), 0],
        [0,              0,             1]
    ])

    R = np.cross(np.cross(R_y, R_x), R_z)
    
    return R

def simulated_positin(xyz, T, R):
    ''' Given target model computes the simulated sensor data
    ARGS:
        xyz (Nx3):    point cloud data of the target model
        T (3x1):      
    '''
    return 0




[[ 0.0000000e+00 -0.0000000e+00  1.2246468e-16]
 [ 0.0000000e+00 -0.0000000e+00  0.0000000e+00]
 [-1.2246468e-16 -0.0000000e+00  0.0000000e+00]]


In [23]:
# Reproducing Experiment 1 - 
#   (x,y,z) = (10,0,0) meters
#   (phi, theta, gamma) = (-180,0,0) degrees
T_0 = np.array([ [33], [0], [0] ])




np.deg2rad(90)
print(np.deg2rad(180))

print()


3.141592653589793
